### PR TITLE
Implemented Dithering

### PR DESCRIPTION
**Pull request by LKGames**
I added a dithering effect, which does a pretty good job at resolving banding without introducing more noise than necessary. 

### 24-bit color, no dithering:
hdr-dither_24-bit_off

### 24-bit color, dithered:
hdr-dither_24-bit_on

### And here is the original image, not limited in color:
hdr-dither_off

------------------
### 16-bit (no dithering):
hdr-dither_16-bit_off

### 16-bit dithered:
hdr-dither_16-bit_on

### 8-bit (no dithering):
hdr-dither_8-bit_off

### 8-bit dithered:
hdr-dither_8-bit_on

### 3-bit (no dithering):
hdr-dither_3-bit_off

### 3-bit dithered:
hdr-dither_3-bit_on

------------------
Note that the "Automatic" option for color depth currently doesn't do anything.
screenshot

### CODE REVIEW

**Comment by Chman** [comment]
Thanks for the PR and the work you've done on this. I did have a go with it but I found out that it doesn't get rid of all of the banding and does add a visible layer of white noise to the final picture, especially in dark areas.

The ability to customize everything and even lower the bit depth is welcomed but out of scope for us, as we want dithering settings to be down to a single checkbox (or none at all and enable it automatically engine-wise, but we prefer to give user at least some control on what's enabled and what's not).

I just pushed a PR (#78) to add support for dithering. I went for blue noise remapped to a triangular distribution as it gave the best results and eliminates most (if not all) the banding in my test scenes without introducing any noticeable noise to the picture compared to a few other techniques I played with. You should definitely try it on your test scene, I'd be curious to know how it works for you.

**Comment by xCyborg** [comment]
This is awesome, does it work with all 16-bit textures and platforms?
Will Unity implement dithering directly at texture level in the importer?

**Comment by LKGames** [comment]
@Chman I tried out your pull request. I agree that it does look better than mine. I'm still seeing some slight banding in certain areas, but I have to look for it to see it. Very nice!
PS: Should I leave this pull request open, or close it?

@xCyborg The post effect only applies to the camera, not the individual textures. If you want to dither your textures, it should be done in an external program (such as Photoshop).

**Comment by Chman** [comment]
I'll close it.

**Pull request closed without merging**
