### PR TITLE
Misc improvements, added inspector support for instantiated profiles

### PR DESCRIPTION
**Pull request by TJHeuvel**
This is the result of us implementing the stack in our game, [Verdun](https://www.1914-1918series.com/). We switched over because we kept running into [this](https://github.com/Unity-Technologies/PostProcessing/issues/465) issue, we arent live yet but it does seem to be resolved. There was another occasional warning about an active rendertexture that dissapeared as an added bonus. 

The learning curve is a bit higher in the v2 stack, i'm still not all to certain how the layers blending works. We dont use them as actual colliders in our scene, it does feel like we're paying a price in complexity for things that we dont use. What did turn out to work extremely well is fading volumes in and out during specific events, for example when you are hit or drowning. Upgrading from v1 was not very hard, some values are in different ranges which is a bit of a gotcha. 

Our [own stack workaround](https://github.com/Unity-Technologies/PostProcessing/issues/516) is working well, it took us a bit to find the correct workflow but the whole postfx stack is now done in two passes. Besides that the `PostProcessResources` asset and being required to call Init with that when using Assetbundles was a bit of a suprise, it would be nice if that was documented better. We replicated that setup for our current stack too. Resources folders arent that nice, but in this case placing these files there would remove this manual step.

Thanks for this super awesome package!

### CODE REVIEW

**Comment by Chman** [comment]
Hi,

Some very interesting changes in there, I'll have to review this more in depth when I get the time but thanks for the PR! It's always great to see how people use it in production and how they tweak it to their needs (and most of the time it makes sense).

> The learning curve is a bit higher in the v2 stack, i'm still not all to certain how the layers blending works

Yeah we need more doc for that, potentially with diagrams and such. Once you understand it it's pretty straightforward (it's no more than the traversal of a big priority override stack) but I can understand it's not necessarily the most easiest thing to understand if you've never worked with a system like that. [This thread](https://github.com/Unity-Technologies/PostProcessing/issues/254) and [this one](https://github.com/Unity-Technologies/PostProcessing/issues/456) explain it a bit more.

> We dont use them as actual colliders in our scene, it does feel like we're paying a price in complexity for things that we dont use.

It's not always obvious at first but except for a slight CPU overhead wrt how the volume framework works, if you don't really use local volumes you won't pay the cost of it.

> What did turn out to work extremely well is fading volumes in and out during specific events, for example when you are hit or drowning.

Because I'm curious, did you rig a custom setup or did you use the builtin QuickVolume stuff or just spawning a temporary volume or... ?

> Besides that the `PostProcessResources` asset and being required to call Init with that when using Assetbundles was a bit of a suprise, it would be nice if that was documented better. We replicated that setup for our current stack too. Resources folders arent that nice, but in this case placing these files there would remove this manual step.

I don't like it either. We, unfortunately, can't use `Resources` folders anymore as they're a big hack with [big implications](https://unity3d.com/learn/tutorials/topics/best-practices/resources-folder). Thing is, because post-processing is generally something you'll have throughout a project's lifetime the `Resources` folder would work fine but we just can't use it anymore. We're still looking for a better way to deal with resources dependencies. So far the "asset" solution is the only one that ticks all the boxes despite all the annoyances on the developer's side.

**Comment by TJHeuvel** [comment]
I really just wanted to commit this to show how we did it, and explain our thought process. I definitely dont expect it all to be accepted (esp. #3890510 which is a mega hack). Thanks a lot for the quick feedback!

> Because I'm curious, did you rig a custom setup or did you use the builtin QuickVolume stuff or just spawning a temporary volume or... ?

In my opinion [QuickVolume](https://github.com/Unity-Technologies/PostProcessing/blob/60365097c16d586180da3382781f517242d5439d/PostProcessing/Runtime/PostProcessManager.cs#L181) should be removed or reworked. Creating a new GameObject in runtime shouldnt be taken lightly, and a name like QuickVolume doesnt really communicate that its expensive. It also hides the object, so without the profiler you wouldnt know whats going on. Maybe CreateVolumeObject would be a better name, hopefully people realise that creating things is bad. 

We have an enum for an PostFXEvent, Hit, AimDownSight, Drowning etc. Each of them has a profile associated, and we make a Volume for every one of them. When the event occurs we lerp in the weight, creating some pretty smooth transitions. It does create a ton of volumes though!  

https://streamable.com/0p1pf
Our designer can easily tweak all effects like this.

**Comment by TJHeuvel** [comment]
Added two more commits, let me know if you'd prefer me to create separate pull request for each issue/feature. Or i can just create an issue without the pull request, if you prefer to look at it yourself.

**Comment by Chman** [comment]
I cherry-picked some of the commits from your PR in #548, namely: ef492c4, 407d17a, 1ec6b99 and c222f14. Thanks again!

I'll skip the `typeof` related commit (46d43f1) as this micro optimization is only valid on pre-4.0 runtimes, on newer ones it's actually faster to use `GetType()` and do comparisons on types directly ([this post](http://higherlogics.blogspot.fr/2013/09/clr-cost-of-dynamic-type-tests.html) shows it pretty well, but you'll find more info on the web). As Unity is in the process of moving toward a more modern runtime I'd rather stick to what we have right now.

I'm keeping this opened as I still have the other commits to look at.

**Comment by TJHeuvel** [comment]
https://streamable.com/lf1kl

This is something that bit us a few times now, where we toggle some effect but dont see it because the overwrite hasnt been enabled in the profile. I understand why both overwrite and Enabled exist, but its still something we did wrong multiple times. 

Not quite sure how to solve this (user) issue, maybe a warning when setting properties for non-overriden fields can save some headache.

**Comment by Chman** [comment]
This is one of these instances where too much flexibility makes it more prone to user errors... Adding a warning isn't straightforward either as it would be easy to have "false warnings" if the volume is overridden by another one anyway.

Eventually one thing I'd like to add is a way to globally enable/disable an effect, no matter how it's setup in the scene. This would make it way easier to have option panels like that.

**Pull request closed without merging**
