### PR TITLE
Vita support

### PR DESCRIPTION
**Pull request by PaulDunning**
Fix for missing XRSettings class on Vita
 
Fixed various shader compile errors when compiling for Vita and define SHADER_API_CONSOLE.

Fix for color grading always appearing monochrome on Vita - the PSP2 cg compiler was using the incorrect version of max() in ApplyCommonGradingSteps(), passing a float as the first parameter caused it to use the single component version of max instead of up-casting to float3 as happens on other platforms, it looks like PSP2 cg is missing the required overload for this function, explicitly casting the first parameter to float3 fixes this.

### CODE REVIEW

**Comment by Chman** [comment]
Good catch on the `max()` stuff.

Quick question: do we really need that `UNITY_3D_TEXTURES_SUPPORTED` define? If PSVita doesn't support texture 3D then it will [never go through this path](https://github.com/Unity-Technologies/PostProcessing/blob/737dee03b849f821ca19ea76135be7c9bd289e9a/PostProcessing/Runtime/Effects/ColorGrading.cs#L177).

Or is it required because the shader compiler fails on texture3D related calls? In this case why not deal with it directly in `PSP2.hlsl` by changing `TEXTURE3D` to use `sampler2D`? It's kind of hacky but as the tex3D code will never get called it will never fail (realistically speaking). It would also be more future-proof in case we need to use tex3D some place else, shaders will still compile but won't be used.

Or maybe I'm missing something...

**Comment by PaulDunning** [comment]
Yes, UNITY_3D_TEXTURES_SUPPORTED was to avoid shader compiler errors on texture3D related calls, I like your idea of redefining the macros to use sampler2D and tex2D instead, it will make the code cleaner, I’ll make that change now.

**Comment by PaulDunning** [comment]
I've pushed the changes to remove UNITY_3D_TEXTURES_SUPPORTED and use texture2D instead.

**Comment by Chman** [comment]
All good, thanks!

**Review by Chman — APPROVED** [review]

**Pull request merged**
